### ISSUE TITLE
xsub の submit_job のエラーメッセージ

### ISSUE THREAD

**Issue by noda50** [crest-cassia/xsub#17]
現状の 各 xsub のsubmit_job のエラーメッセージがわかりにくすぎる。
なにが問題なのかの情報が、全く失われている。

とりあえず、abci.rb については、多少、わかりやすくエラーが表示されるようにした。（特に web interface からわかるように)

**Comment by yohm** [comment]
現状はoacisからエラーがちゃんと確認できるようになっていると思いますので、closeしたいと思います。

**Comment by tkmnet** [comment]
本件ですが，現状OACISの方でxsub自体の標準エラー出力をハンドリングできているということでしょうか？

**Comment by yohm** [comment]
@tkmnet そういう問題でしたか。問題が認識できていませんでした。確かに標準エラー出力をxsubのJSONに含めておいた方がデバッグしやすそうですね。今後実装していきたいと思います。（もしよかったらxsubへのPRも大歓迎です。）

**Comment by tkmnet** [comment]
勘違いしていたことがあって，２つのPRにわけました．
まず，エラーの場合には例外を投げるようになっているようになっているため，JSONは出力されませんでした．
なので，例外のメッセージをハンドルするために，標準エラー出力をハンドリングしていれば，例外の直前にスケジューラの標準エラー出力は表示されそうでした．
ただどこにそのエラーが書かれているのかはわかりにくいです．
したがって，野田先生のサジェスト部分では例外メッセージに標準エラー出力を導入するところまででした．
そこまでで済ました上で，RSpecが正常動作するようにした変更が #33 になります．

ただ，やはりスタックトレースを含めたエラーメッセージでは，読みにくいと思うので，#34 で強制的にJSONで出力するモードを追加してみました．
環境変数のXSUB_JSONを0にした場合有効化されます．
モード切替が必要になっているのは，`xstat` など通常の挙動の出力が現在の実装と異なってしまう部分があるためです．

**Comment by yohm** [comment]
@tkmnet 説明とPRありがとうございます。
ちょっとまだ「解決したい問題は何か」、「それに対してどのような対策を施したのか」がわからないのでもう少し説明していただけないでしょうか？

1. まず大前提として、OACISから利用した時にトラブルシューティングしづらいという問題を解決しようとしているんですよね？それともxsubを単体で使う場合の問題の話をしていますか？（web interface...と書いてあったのでOACISから使う際の話だと想定しています。）
2. スケジューラのコマンド(qsub)が0以外の値を返した時に、xsubが例外を投げて異常終了するようになっています。その際に「xsubの標準エラー出力にqsubの標準エラー出力が含まれないので困っている」ということでよろしいでしょうか？そのため、「xsubからqsubを実行する際に、qsubから出力された標準エラー出力をxsubで読んで、xsubの標準エラーとして出力するようにした」のが #33 の変更ということだと推測しましたが、あってますでしょうか？
3.  `ただ，やはりスタックトレースを含めたエラーメッセージでは，読みにくいと思うので` という部分がわからないです。想像するに、「xsubからqsubの標準エラー出力も出力するようにはしたが、xsubの標準エラー出力にはxsubのスタックトレースも出力されてしまうのでエラーの箇所が分かりづらい。」という問題だと推察します。あってますでしょうか？
4. 上記の推察が合っているとして話を進めさせてもらうと、なぜJSON出力にするとエラーが読みやすくなるのでしょうか？どのように出力が変わるのか例を示せますか？
5. JSONで出力したとしてもOACISはそのJSONをパースするようにはなっていません。ということはやはりコマンドラインから使う場合の話をしていますか？

**Comment by tkmnet** [comment]
@yohm 
すみません．確かにそれぞれの前提を書いていなかったのでわかりにくかったです．
私の場合はxsubを単体で（別アプリから）使用させてもらっているので，そこからの要望も混ざってしまいました．

1. #33 については特に現状のOACISからで，#34 は特に単体（別アプリ）での問題のためです．
2. はい．（標準エラー出力には変わりないので，標準エラー出力の前半にはqsubのエラーは含まれそうですが，メッセージがスタックトレースを跨がないので，比較的わかりやすくなると思います．）
3. はい．
4. 5. 上位アプリ（OACISや別アプリ）でJSONでの出力をパースするようにすればxsubのスタックトレースと分離でき，エラーを読みやすくできるため，上位アプリの利便性を向上できるのではと思い，#34 を提案させていただきました．

**Comment by yohm** [comment]
@tkmnet ありがとうございます。おかげさまで意図がよく分かりました。 #33 はマージしました。 #34 にはコメントを返信したので、みてもらえますか？
