### ISSUE TITLE
xstatにキャッシュ/一括請求機能が欲しい

### ISSUE THREAD

**Issue by tkmnet** [crest-cassia/xsub#24]
xstatについてですが，一覧取得できる場合は一定時間（数秒）一覧取得したものを保持して，
なるべくqstatなどのキューイングシステムのコマンドを大量発行してしまわないモードがあるとうれしいです．

現在の実装だとジョブ番号ごとにqstatのようなステータス確認コマンドを実行するようになっているかと思います．
この状態だと例えば100ジョブが流れていた場合，キューイングシステムのコマンドをポーリング時間ごとに100回連続で発行してしまうことになります．
以前使用していた計算資源ではライセンスの制限などにより，コマンドの発行を1分に10回程度にするようにといった制限がありました．
また，キューイングシステムに大量にジョブが積まれている場合は，ステータス確認コマンドの応答が遅くなりがちなので，
それに対応できるようなインタフェースがあるとうれしいと思っています．

**Comment by yohm** [comment]
おっしゃる通り、これは問題ですね。どうにかしたいのですが、本当にキャッシュすることでこの問題が解決しますか？ジョブが100ある時には、頻度は下がっても結局qstatが100回実行されてしまうので、問題が解決しないように思います。

`xstat {job1} {job2} {job3} {job4} ...` のように複数のジョブに対して１コマンドで情報を取れるような方法があれば解決できると思いますが、使っているスケジューラでそのような一括取得ができるようなコマンドがありますか？

**Comment by tkmnet** [comment]
たとえばtorqueやUGEの場合は，`qstat` を叩くと以下のような一覧が取得できますので，その一覧を一定時間保持すれば，たとえば100ジョブあるなら，100ジョブ分を1回のコマンド発行におさえることができるかと思います．
```
[aaa10259dp@es2 ~]$ o-qstat
job-ID     prior   name       user         state submit/start at     queue                          jclass                         slots ja-task-ID 
------------------------------------------------------------------------------------------------------------------------------------------------
   6724409 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:14:30 gpu@g0341                                                        80        
   6724414 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:15:36 gpu@g0342                                                        80        
   6724415 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:15:36 gpu@g0343                                                        80        
   6724416 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:16:07 gpu@g0344                                                        80        
   6724418 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:16:07 gpu@g0345                                                        80        
   6724420 0.25586 xxx19_jo aaa10000xx   r     03/25/2021 19:16:07 gpu@g0346                                                        80 
```

**Comment by yohm** [comment]
このコマンドを使うようにするのがいいですね。
ただし、結果を一定時間キャッシュをするよりは、結果を`xstat {job1} {job2} {job3} {job4} ...`のように一括でクエリを発行できるようにする方が思わぬバグを作らないようにするためにも良いと思います。
OACISからは、xstatコマンドを複数のジョブにたいして１回だけ呼ぶようにして、実際にコマンドが呼ばれる回数を少なくすることはできると思います。少し考えてみます。（すでに実装のアイデアがあるのなら、提案をpull requestの形で送っていただいてもいいです。）

**Comment by tkmnet** [comment]
確かにキャッシュするより，一括請求したほうがよさそうですね．少し実装を試してみます．
