### ISSUE TITLE
Which model should have default values of host paremters

### ISSUE THREAD

**Issue by takeshi-uchitane** [crest-cassia/xsub#4]
### Problem
Now xsub model has default values of host parameters.
However, it is acceptable that simulator model has the default values.
It is because the default values are usually reset in each simulator or each run.

### Solution
Remove default keys form xsub template.
Simulation model has default host parameter values.
Set default values in assigning a host to a simulator in host edit page or in simulator edit page.

**Comment by yohm** [comment]
各simulatorごとにhost parameterを保存するようにOACISを更新した。
